export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENT_LOADING = 'SET_INGREDIENT_LOADING';
export const GET_RECIPES = 'GET_RECIPES';
export const SET_RECIPE_LOADING = 'SET_RECIPE_LOADING';
