version: "3.3"
services:
  app:
    build: .
    command: npm run start
    depends_on:
      - db
    ports:
      - 3000:3000
    links:
      - "db:db"
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: solarnasti
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: nasti_database